title = "Aerobatic + Forestry CMS Demo"
baseurl = "http://example.org/"
languageCode = "en-us"
theme = "hemingway2"

[params]

[params.highlight]
style = "github"
languages = ["markdown", "html", "js"]

[[params.social]]
url = "https://github.com/aerobatic"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/aerobaticapp"
fa_icon = "fa-twitter"
